compilers=&guppy
defaultCompiler=guppy015

supportsExecute=false
supportsBinary=false
supportsBinaryObject=false
interpreted=false
compilerType=guppy
postProcess=
options=
needsMulti=false
disasmScript=

instructionSet=llvm
demangler=c++filt
objdumper=objdump
supportsAsmDocs=true

stubText=main():
isSemVer=true

group.guppy.compilers=guppy015:guppy014
group.guppy.baseName=Guppy
group.guppy.exe=guppyc

# We specify 'uv' as a compiler here.
# Internally, we set the `guppylang` library version to the specified semver.
# And run a custom script to execute the code.
compiler.guppy015.semver=0.15.0
compiler.guppy014.semver=0.14.0

