compilers=&guppy
defaultCompiler=guppy015
instructionSet=python
supportsBinary=true
supportsBinaryObject=true
isSemVer=true

group.guppy.compilers=guppy015:guppy014
group.guppy.baseName=Guppy

# We specify 'uv' as a compiler here.
# Internally, we set the `guppylang` library version to the specified semver.
# And run a custom script to execute the code.
compiler.guppy015.exe=guppyc
compiler.guppy015.semver=0.15.0
compiler.guppy014.exe=guppyc
compiler.guppy014.semver=0.14.0

interpreted=false
compilerType=guppy
objdumper=objdump
demangler=
postProcess=
options=
needsMulti=false
supportsExecute=true
stubText=from guppylang import guppy\n@guppy\nmain():
disasmScript=

