compilers=&guppy
defaultCompiler=guppy015
instructionSet=python

group.guppy.compilers=guppy015:guppy014
group.guppy.isSemVer=true
group.guppy.baseName=Guppy

# We specify 'uv' as a compiler here.
# Internally, we set the `guppylang` library version to the specified semver.
# And run a custom script to execute the code.
compiler.guppy015.exe=uv
compiler.guppy015.semver=0.15.0
compiler.guppy014.exe=uv
compiler.guppy014.semver=0.14.0

supportsBinary=false
interpreted=true
compilerType=guppy
objdumper=
demangler=
postProcess=
options=
needsMulti=false
supportsExecute=true
stubText=from guppylang import guppy\n@guppy\nmain():
disasmScript=
